import JSZip from "jszip";

export interface ComponentExportFiles {
  title: string;
  slug: string;
  reactCode: string;
  htmlCode: string;
  cssCode: string;
  jsCode: string;
  vueCode?: string;
  svelteCode?: string;
  dependencies?: string[];
}

/**
 * Downloads a structured ZIP archive containing files for the component:
 * - React component (e.g. Component.tsx)
 * - HTML, CSS, JS files
 * - Vue & Svelte components
 * - README.md with installation & usage guidelines
 */
export async function downloadComponentZip(comp: ComponentExportFiles): Promise<void> {
  const zip = new JSZip();

  const folderName = `xui-${comp.slug}`;
  const root = zip.folder(folderName) || zip;

  // 1. React / Next.js folder
  const reactFolder = root.folder("react");
  if (reactFolder) {
    reactFolder.file(`${capitalize(comp.slug)}.tsx`, comp.reactCode);
  }

  // 2. Vanilla Web folder (HTML/CSS/JS)
  const vanillaFolder = root.folder("vanilla");
  if (vanillaFolder) {
    vanillaFolder.file("index.html", comp.htmlCode);
    vanillaFolder.file("styles.css", comp.cssCode);
    vanillaFolder.file("script.js", comp.jsCode);
  }

  // 3. Vue folder
  if (comp.vueCode) {
    const vueFolder = root.folder("vue");
    if (vueFolder) {
      vueFolder.file(`${capitalize(comp.slug)}.vue`, comp.vueCode);
    }
  }

  // 4. Svelte folder
  if (comp.svelteCode) {
    const svelteFolder = root.folder("svelte");
    if (svelteFolder) {
      svelteFolder.file(`${capitalize(comp.slug)}.svelte`, comp.svelteCode);
    }
  }

  // 5. README.md
  const readmeContent = `# ${comp.title} - XUI Component

${comp.title} is a handcrafted animated UI component from **XUI** library.
Designed & curated by Aymen.

## Required Dependencies:
\`\`\`bash
npm install ${comp.dependencies && comp.dependencies.length > 0 ? comp.dependencies.join(" ") : "motion lucide-react"}
\`\`\`

## React Usage:
\`\`\`tsx
import ${capitalize(comp.slug)} from './${capitalize(comp.slug)}';

export default function Example() {
  return <${capitalize(comp.slug)} />;
}
\`\`\`

## Vanilla HTML / CSS / JS Usage:
Simply include \`styles.css\` in the \`<head>\` and \`script.js\` at the end of \`<body>\`.

---
© XUI UI Platform - Created with ❤️ by Aymen
`;

  root.file("README.md", readmeContent);

  // Generate blob & trigger browser download
  const blob = await zip.generateAsync({ type: "blob" });
  triggerDownload(blob, `${folderName}.zip`);
}

/**
 * Downloads a single formatted Markdown (.md) documentation file
 */
export function downloadComponentMarkdown(comp: ComponentExportFiles): void {
  const mdContent = `# ${comp.title} (XUI Component)

> Handcrafted animated component by **Aymen** for **XUI**.

## Dependencies
\`\`\`bash
npm install ${comp.dependencies && comp.dependencies.length > 0 ? comp.dependencies.join(" ") : "motion lucide-react"}
\`\`\`

---

## 1. React (TypeScript + Tailwind)
\`\`\`tsx
${comp.reactCode}
\`\`\`

---

## 2. HTML
\`\`\`html
${comp.htmlCode}
\`\`\`

## 3. CSS
\`\`\`css
${comp.cssCode}
\`\`\`

## 4. JavaScript
\`\`\`javascript
${comp.jsCode}
\`\`\`

${
  comp.vueCode
    ? `---

## 5. Vue
\`\`\`vue
${comp.vueCode}
\`\`\`
`
    : ""
}
${
  comp.svelteCode
    ? `---

## 6. Svelte
\`\`\`svelte
${comp.svelteCode}
\`\`\`
`
    : ""
}
---
Generated by XUI Platform (Created by Aymen)
`;

  const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8" });
  triggerDownload(blob, `${comp.slug}.md`);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function capitalize(str: string) {
  return str
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}
